version: "3.7"

services:
  api:
    build:
      context: api

  web:
    build:
      context: web
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
      - yarn-cache:/app/node_modules

volumes:
  yarn-cache: {}
