version: "3.7"

services:
  api:
    build:
      context: api
    ports:
    - 4000:4000
    depends_on:
      - postgres

  web:
    build:
      context: web
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
      - yarn-cache:/app/node_modules

  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: vshuki
      POSTGRES_USER: vshuki
      POSTGRES_PASSWORD: vshuki
    volumes:
      - pgsql-data:/var/lib/pgsql

volumes:
  yarn-cache: {}
  pgsql-data: {}
